# Generated by Django 3.1.5 on 2021-01-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_date', models.DateField()),
                ('story_keyword', models.CharField(max_length=255, null=True)),
                ('story_title', models.CharField(max_length=255)),
                ('story_content', models.TextField()),
            ],
        ),
    ]
